// default package
// Generated 29 ene 2025, 16:10:08 by Hibernate Tools 6.5.1.Final

/**
 * CurrentDeptEmp generated by hbm2java
 */
public class CurrentDeptEmp implements java.io.Serializable {

	private CurrentDeptEmpId id;

	public CurrentDeptEmp() {
	}

	public CurrentDeptEmp(CurrentDeptEmpId id) {
		this.id = id;
	}

	public CurrentDeptEmpId getId() {
		return this.id;
	}

	public void setId(CurrentDeptEmpId id) {
		this.id = id;
	}

}
