// default package
// Generated 29 ene 2025, 16:10:08 by Hibernate Tools 6.5.1.Final

/**
 * DeptManagerId generated by hbm2java
 */
public class DeptManagerId implements java.io.Serializable {

	private String deptNo;
	private int empNo;

	public DeptManagerId() {
	}

	public DeptManagerId(String deptNo, int empNo) {
		this.deptNo = deptNo;
		this.empNo = empNo;
	}

	public String getDeptNo() {
		return this.deptNo;
	}

	public void setDeptNo(String deptNo) {
		this.deptNo = deptNo;
	}

	public int getEmpNo() {
		return this.empNo;
	}

	public void setEmpNo(int empNo) {
		this.empNo = empNo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DeptManagerId))
			return false;
		DeptManagerId castOther = (DeptManagerId) other;

		return ((this.getDeptNo() == castOther.getDeptNo()) || (this.getDeptNo() != null
				&& castOther.getDeptNo() != null && this.getDeptNo().equals(castOther.getDeptNo())))
				&& (this.getEmpNo() == castOther.getEmpNo());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getDeptNo() == null ? 0 : this.getDeptNo().hashCode());
		result = 37 * result + this.getEmpNo();
		return result;
	}

}
