// default package
// Generated 29 ene 2025, 16:10:08 by Hibernate Tools 6.5.1.Final

/**
 * DeptEmpLatestDate generated by hbm2java
 */
public class DeptEmpLatestDate implements java.io.Serializable {

	private DeptEmpLatestDateId id;

	public DeptEmpLatestDate() {
	}

	public DeptEmpLatestDate(DeptEmpLatestDateId id) {
		this.id = id;
	}

	public DeptEmpLatestDateId getId() {
		return this.id;
	}

	public void setId(DeptEmpLatestDateId id) {
		this.id = id;
	}

}
